# encoding: utf-8

require 'mongo_odm/core_ext/array'
require 'mongo_odm/core_ext/big_decimal'
require 'mongo_odm/core_ext/boolean'
require 'mongo_odm/core_ext/bson/object_id'
require 'mongo_odm/core_ext/bson/ordered_hash'
require 'mongo_odm/core_ext/class'
require 'mongo_odm/core_ext/date'
require 'mongo_odm/core_ext/date_time'
require 'mongo_odm/core_ext/false_class'
require 'mongo_odm/core_ext/float'
require 'mongo_odm/core_ext/hash'
require 'mongo_odm/core_ext/hash_with_indifferent_access'
require 'mongo_odm/core_ext/integer'
require 'mongo_odm/core_ext/nil_class'
require 'mongo_odm/core_ext/numeric'
require 'mongo_odm/core_ext/string'
require 'mongo_odm/core_ext/symbol'
require 'mongo_odm/core_ext/time'
require 'mongo_odm/core_ext/true_class'
